💾  ← &fras "example.txt"
🗒️ ← ⊜□∘¬⊸⦷"\n\n"💾

FindAfterPages   ← □ ▽ ≠ 0 . × ⌕ ⊃(∘|°⊟⍉⍆⋅⊙)
IncorrectPage    ← >0/+∈
GetPages         ← ⋕⊜□≠@, .
CheckPage ← (
  IncorrectPage °□:,⬚0get⊙, °⊂ ⇌
  ⇌ ⨬(∘|[¯1]))
MiddlePageNumber ← ⊡ ⌊ ÷ 2 ⧻ .
GetScore ← (
  :⟜⍢(CheckPage|¬≍1⧻)
  ◌:⨬(0|MiddlePageNumber) >0/+
)

:⊜□∘¬⊸⦷@\n°□:⋕≡(⊜□≠@|). ⊜∘¬⊸⦷@\n°□°⊟🗒️
map⟜≡FindAfterPages ⊙¤ ⊃(◌:◴°⊟⍉⍆|∘)

/+ ⍚GetScore :¤: ⍚GetPages :
